### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by qq272574497** [SamsungLabs/zero-cost-nas#22]
![wrong](https://user-images.githubusercontent.com/66626324/232320522-eccc43eb-11f6-4adb-9254-cda696f61b36.jpg)
What should I do if I keep reporting errors?

**Comment by vaenyr** [comment]
Hi, you can try a lower batch size, but the code should already try it out automatically (you can see it happening when it says that an oom error has been caught). After that another option is to try to lower input resolution (if possible in your case).

In general, how much memory you might need depends on: batch size, input size (input resolution), model architecture. I'm guessing it doesn't make sense to change the last one, so that leaves you with the two options mentioned above.

As a rule of thumb, if you can train a model using certain options, you should be able to compute any zc proxy using the same options.

**Comment by qq272574497** [comment]
def find_measures(net_orig,                  # neural network
                  dataloader,                # a data loader (typically for training data)
                  dataload_info,             # a tuple with (dataload_type = {random, grasp}, number_of_batches_for_random_or_images_per_class_for_grasp, number of classes)
                  device,                    # GPU/CPU device used
                  loss_fn=F.cross_entropy,   # loss function to use within the zero-cost metrics
                  measure_names=None,        # an array of measure names to compute, if left blank, all measures are computed by default
                  measures_arr=None):        # [not used] if the measures are already computed but need to be summarized, pass them here

When I finished running this code, the GPU memory did not decrease. Do I need to release relevant variables?

**Comment by qq272574497** [comment]
![result](https://user-images.githubusercontent.com/66626324/232429030-e67fdf00-1e97-45d9-9076-7c90fc6d0520.jpg)

I delete this line of code, GPU memory does not leak; Can I delete this line of code？

**Comment by vaenyr** [comment]
Yes, it should be fine to remove this line - the only possible side-effect is that the passed network might be in a different state after this function finishes.

**Comment by vaenyr** [comment]
Hi, has the issue been resolved?

**Comment by qq272574497** [comment]
> Hi, has the issue been resolved?

yes,del net_orig = net_orig.to(device).train()
