### ISSUE TITLE
Problem about the calculation of synflow.

### ISSUE THREAD

**Issue by pingguokiller** [SamsungLabs/zero-cost-nas#7]
Hello! I'm very interested in your work.

In Section 3.2.1 "SNIP, GRASP AND Synaptic Flow",  synflow is formulated without abs operation.

However, for the code in "synflow.py",  synflow is calculated by "torch.abs(layer.weight * layer.weight.grad)".

I wonder about the role and the reference of the abs operation. Why should we use it? I try to refer to the original paper "Pruning neural networks without any data by iteratively conserving synaptic flow", but I still have no idea.

**Comment by vaenyr** [comment]
Also, apologies for a late reply, for some reason I missed a notification about your issue and only saw it today!

**Comment by vaenyr** [comment]
Actually, I took a closer look at the code and it turns out I got it wrong, although the way of thinking seems right in general.
Because parameters are modified with `torch.no_grad` before forward pass, `.backward()` will actually calculate `dRsf/dabs(p) * abs(p)` and it should always be positive so the abs is simply not necessary.(I've run some short tests with resnet18 and all scores remain positive even without the abs).
If the derivative was in fact calculated with respect to the original params like I originally assumed (i.e., the case `dRsf/dp * abs(p)` then we'd actually need the extra abs as explained in my previous reply - perhaps that's why it appeared in the synflow repo in the first place?

**Comment by pingguokiller** [comment]
> Actually, I took a closer look at the code and it turns out I got it wrong, although the way of thinking seems right in general. Because parameters are modified with `torch.no_grad` before forward pass, `.backward()` will actually calculate `dRsf/dabs(p) * abs(p)` and it should always be positive so the abs is simply not necessary.(I've run some short tests with resnet18 and all scores remain positive even without the abs). If the derivative was in fact calculated with respect to the original params like I originally assumed (i.e., the case `dRsf/dp * abs(p)` then we'd actually need the extra abs as explained in my previous reply - perhaps that's why it appeared in the synflow repo in the first place?

Thanks very much for your useful reply!
